### ISSUE TITLE
SyntaxError on Lambda function in ./run_demo.sh / infer_single.py

### ISSUE THREAD

**Issue by Gtxefc** [thmoa/octopus#10]
**run_demo.sh code:**
```
#!/usr/bin/env bash
python3 infer_single.py sample data/sample/segmentations data/sample/keypoints --out_dir out
```

**Error:**
```
Traceback (most recent call last):
  File "infer_single.py", line 9, in <module>
    from model.octopus import Octopus
  File "/media/r/edata/code/nns/pose_det/octopus/model/octopus.py", line 206
    self.laplacian = Lambda(lambda (v0, v1): compute_laplacian_diff(v0, v1, self.faces), name='laplacian')(
                                   ^
SyntaxError: invalid syntax
```

Any tips / suggestions? I'm using python3.7 and Ubuntu 19.04 and had to install dirt directly but it worked.

**Comment by thmoa** [comment]
might be python 3 syntax.  the project has only been tested under python 2. feel free to submit PR.

**Comment by QHan1st** [comment]
> **run_demo.sh code:**
> 
> ```
> #!/usr/bin/env bash
> python3 infer_single.py sample data/sample/segmentations data/sample/keypoints --out_dir out
> ```
> 
> **Error:**
> 
> ```
> Traceback (most recent call last):
>   File "infer_single.py", line 9, in <module>
>     from model.octopus import Octopus
>   File "/media/r/edata/code/nns/pose_det/octopus/model/octopus.py", line 206
>     self.laplacian = Lambda(lambda (v0, v1): compute_laplacian_diff(v0, v1, self.faces), name='laplacian')(
>                                    ^
> SyntaxError: invalid syntax
> ```
> 
> Any tips / suggestions? I'm using python3.7 and Ubuntu 19.04 and had to install dirt directly but it worked.

i meet the same questions as yours.had you resolved it?
@Gtxefc
