### ISSUE TITLE
SMPL offsets estimation

### ISSUE THREAD

**Issue by jgallegov** [thmoa/octopus#19]
Hello, 
Thank  you for this work. I am trying to get the SMPL offsets estimation and I have not figured out how can I extract them in a file. Please, can you tell me how can I obtain them?

Thank you,

**Comment by quyanqiu** [comment]
@jgallegov if you read code carefully ,in infer_batch.py or infer_single.py ,the result of model prediction result is a dictionary,some code likes pred=model.predict(...) (I am not sure the detail but you may find these code),you can obtain vertices like vertics_0=pred['vertices'][0]（in infer_batch.py pred['vertices'] is a list that contain all frame vertices,here is frame=0 vertics for instant）,offset space offset=pred['offset'] and other smpl attribute. after that you can save them to pkl or numpy .npy binary file
for the detail you can check ./model/octopus.py for more information.
