### ISSUE TITLE
Camera Focus Doesn't Match

### ISSUE THREAD

**Issue by sking8** [thmoa/octopus#21]
I used octopus to generate the vertices in each frame, however, the focal length there was some default value [1080,1080]. So the vertices are not in the real relative position to camera and the generated visibility map gives horrible result. Can you change the code for octopus to take real camera focal length?

**Comment by thmoa** [comment]
The focal length is the one Octopus has been trained on. If you want to feed in photos with a much different focal length you would have to retrain Octopus. I do not know what you mean with "generated visibility map". The code is provided "as is" and I am not able to take feature requests.
