### ISSUE TITLE
Output Inconsistency when using the batch version 

### ISSUE THREAD

**Issue by MaxMayya** [thmoa/octopus#28]
Thank you for sharing this great work.
I recently ran into the following issue: 

- I used the `infer_batch.py` on 3 sets of images
- the 3 sets are identical (the 8 segmentations/keypoints of set1, set2 and set3 are identical)
- `infer_batch.py` executed successfully with three meshes
- **RESULTS** the three meshes are not identical: slight pose (and maybe shape) differences

To debug the problem out of the box, I compared the three meshes with the output of `infer_single.py` (using the same default arguments, i.e. same optimisation steps). I found that only the firstly executed mesh of the `infer_batch.py` output is identical to that of `infer_single.py`. 

Does it mean that the model's weights are updated after the first execution? Otherwise, what could be the reason of such behaviour?

Thanks

**Comment by thmoa** [comment]
That is an unexpected behaviour that I cannot comment on. I can only speculate what is the reason. Maybe some numerical issues?

**Comment by lll-gen** [comment]
I found the same problem: Output Inconsistency when using the same input.
,I compared the three meshes with the output of the same input ,I found  there are differences between the three output.
Is there a random initialization？
