### ISSUE TITLE
ValueError: Incompatible shapes between op input and calculated input gradient.

### ISSUE THREAD

**Issue by punjal97** [thmoa/octopus#3]
Hi,
Awesome code!
Actually running the bash script is giving "ValueError: Incompatible shapes between op input and calculated input gradient."
I tried running both the scripts and the same error comes!

Environment:
OS - Ubuntu 16.04
Tensorflow_gpu: 1.12.2
Keras: 2.2.4

Optimizing for Pose is running fine, but Optimizing for Shape is giving error.

![Screenshot from 2019-04-25 12-46-32](https://user-images.githubusercontent.com/13464149/56721494-9f628280-6762-11e9-83ce-93d9d17bc047.png)

Any help would be great!
Thanks.

**Comment by thmoa** [comment]
This error might be related to DIRT. The code as provided works on our systems. If you find a bug, please open a pull request.
