### ISSUE TITLE
Can you give me the  version of tensorflow and keras to run your code

### ISSUE THREAD

**Issue by vigorbird** [thmoa/octopus#31]
I use tensorflow-gpu 1.14.0, keras 2.2.4, opencv-python 4.4.0.46. But it reports:
Using TensorFlow backend.
Traceback (most recent call last):
  File "infer_single.py", line 9, in <module>
    from model.octopus import Octopus
  File "/home/fyytim/octopus/octopus/model/octopus.py", line 206
    self.laplacian = Lambda(lambda (v0, v1): compute_laplacian_diff(v0, v1, self.faces), name='laplacian')(
                                   ^
SyntaxError: invalid syntax

**Comment by thmoa** [comment]
see `requirements.txt`

**Comment by AndreyStille** [comment]
> I use tensorflow-gpu 1.14.0, keras 2.2.4, opencv-python 4.4.0.46. But it reports:
> Using TensorFlow backend.
> Traceback (most recent call last):
> File "infer_single.py", line 9, in 
> from model.octopus import Octopus
> File "/home/fyytim/octopus/octopus/model/octopus.py", line 206
> self.laplacian = Lambda(lambda (v0, v1): compute_laplacian_diff(v0, v1, self.faces), name='laplacian')(
> ^
> SyntaxError: invalid syntax

Hi, please help if you have found the apropriate version. I faced similar issue, requirements.txt from repository is useless
