### ISSUE TITLE
Training code without the dataset

### ISSUE THREAD

**Issue by atabak-cve** [thmoa/octopus#32]
I know you have mentioned that it is not planned to share the training code because of the dataset license.
But is it possible to publish only the training code (and maybe only the structure of the train dataset), without sharing the data itself? It will be certainly useful, even if the training code is not as clean as the current repo 😄

**Comment by thmoa** [comment]
I don't longer have access to the code base as I left the institute. I also doubt that it will be very useful without the data since it is very much tailored for the dataset.
