### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by SriGanesh130** [thmoa/octopus#9]
OS : ubuntu 16
python3
Getting error in loading of pickle file(assets/smpl_sampling.pkl). giving No module named 'numpy.core._multiarray_umath'.
'models/octopus.py line 169'

**Comment by SriGanesh130** [comment]
After updating numpy to 1.16.3 it's working.
for python3
we have to include
pkl.load(f, encoding='latin1')


Thank You

**Comment by OOF-dura** [comment]
> After updating numpy to 1.16.3 it's working.
> for python3
> we have to include
> pkl.load(f, encoding='latin1')
> 
> Thank You

Did you successfully ran Octopus on py3.6? Thanks! I tried 3.7 3.6, all failed.
